spring.application.name=financebuddy

# Set Server Port 
server.port=8080

# Set Session name
server.servlet.session.cookie.name=FINANCEBUDDY_SESSION

# jsp View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Mock data ke liye (bina database ke)
app.use.mock.data=true